# Generated by Django 2.2.24 on 2021-10-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Type of role')),
                ('hourlyPay', models.IntegerField(verbose_name='Payment per hour for a role')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startHour', models.TimeField(verbose_name='Time started working')),
                ('endHour', models.TimeField(verbose_name='Time started working')),
                ('amount', models.IntegerField(verbose_name='automatic calculated payment per role')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=120, verbose_name='Last Name')),
                ('studentID', models.IntegerField(verbose_name='ID of student')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of student')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of Timesheet')),
                ('year', models.DateTimeField(verbose_name='Year of Timesheet')),
                ('shifts', models.ManyToManyField(blank=True, to='timesheet.Shift')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='studentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.Student'),
        ),
    ]
