# Generated by Django 2.2.24 on 2021-10-26 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(default=datetime.date.today(), verbose_name='Date of work'),
        ),
    ]
