# Generated by Django 2.2.24 on 2021-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount paid'),
        ),
    ]
