# Generated by Django 3.2.8 on 2021-10-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20211026_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='payment',
            new_name='amount',
        ),
    ]
