# Generated by Django 2.2.24 on 2021-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20211026_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of work'),
        ),
    ]
