# Generated by Django 3.2.8 on 2021-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_rename_payment_shift_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='amount',
        ),
        migrations.AlterField(
            model_name='shift',
            name='endHour',
            field=models.DateTimeField(verbose_name='Time finished working'),
        ),
    ]
