# Generated by Django 2.2.24 on 2021-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20211026_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='amount',
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='endHour',
            field=models.DateTimeField(verbose_name='Time started working'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='startHour',
            field=models.DateTimeField(verbose_name='Time started working'),
        ),
    ]
