# Generated by Django 2.2.24 on 2021-11-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_auto_20211108_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('Student', 'Student'), ('Verifier', 'Verifier'), ('Payer', 'Payer')], default='Student', max_length=120, verbose_name='Type of role'),
        ),
    ]
