# Generated by Django 2.2.24 on 2021-11-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_auto_20211108_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Type of role'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timesheet.Roles'),
        ),
    ]
