# Generated by Django 2.2.24 on 2021-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='title',
        ),
        migrations.AddField(
            model_name='userroles',
            name='name',
            field=models.CharField(default='Student', max_length=120, verbose_name='Title'),
        ),
    ]
