# Generated by Django 2.2.24 on 2021-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
