# Generated by Django 2.2.24 on 2021-11-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20211103_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.UserRoles'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
    ]
