# Generated by Django 2.2.24 on 2021-11-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20211108_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='salary',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.UserRoles'),
        ),
    ]
