# Generated by Django 2.2.24 on 2021-11-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20211108_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.UserRoles'),
        ),
    ]
